// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDXbO5UhFgft8hWGb81o7DfUNmbHmSsNNI',
    appId: '1:873249854709:web:19d969d301f9fc7cc921bc',
    messagingSenderId: '873249854709',
    projectId: 'bookswap-1aa70',
    authDomain: 'bookswap-1aa70.firebaseapp.com',
    storageBucket: 'bookswap-1aa70.firebasestorage.app',
    measurementId: 'G-F2YQSFRPD0',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDKthpOAn5nIJMFed-c4E_OrP_oR2RGIRM',
    appId: '1:873249854709:android:ca2a39bd62a93e93c921bc',
    messagingSenderId: '873249854709',
    projectId: 'bookswap-1aa70',
    storageBucket: 'bookswap-1aa70.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBuvddzNoh4BgZrmJatowiJUtVcP9Tivwg',
    appId: '1:873249854709:ios:4a3c628c80a94f4fc921bc',
    messagingSenderId: '873249854709',
    projectId: 'bookswap-1aa70',
    storageBucket: 'bookswap-1aa70.firebasestorage.app',
    iosBundleId: 'com.example.bookswapApp',
  );
}
